name: Publish on version change (JSON)

on:
  push:
    branches:
      - stable
    paths:
      - 'library.json'

jobs:
  publish_package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Shell
        run: sudo apt-get install -y jq

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Check if version has changed
        id: check_version
        run: |
          source scripts/version_utils.sh

          CURRENT_VERSION=$(get_version_from_json)
          echo "Current version: $CURRENT_VERSION"

          if git diff HEAD^ HEAD --quiet --exit-code -- library.json; then
            echo "No changes in library.json. Skipping package publish."
            exit 0
          else
            PREVIOUS_VERSION=$(get_version_from_json HEAD^)
            if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
              echo "VERSION=$CURRENT_VERSION" >> $GITHUB_ENV
            else
              echo "Version has not changed. Skipping package publish."
              exit 0
            fi
          fi

      - name: Publish package
        if: env.VERSION != ''
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: |
          echo "Publishing package for version $VERSION"
          pio pkg publish --non-interactive